image: jakzal/phpqa:php8.0

variables:
  TIMEOUT_SECONDS: 1

before_script:
  - composer --version
  - composer install

cache:
  paths:
    - vendor/

stages:
  - Security
  - Quality

security-checker:
  stage: Security
  script:
    - local-php-security-checker composer.lock
  allow_failure: false

phpcs:
  stage: Quality
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: true

phpstan:
  stage: Quality
  script:
    - phpstan analyse ./src
  allow_failure: true

# code-quality:
#   image: docker:latest
#   stage: Quality
#   variables:
#     DOCKER_DRIVER: overlay
#   services:
#     - docker:dind
#     - composer:latest
#   script:
#     - docker pull codeclimate/codeclimate
#     - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
#     - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
#   artifacts:
#     expire_in: 30 days
#     paths: [code-climate.json]
#   allow_failure: true

twig-lint:
  stage: Quality
  script:
    - twig-lint lint ./templates
  allow_failure: true
