image: jakzal/phpqa:php8.0

variables:
  TIMEOUT_SECONDS: 1

before_script:
  - composer --version
  - composer install

cache:
  paths:
    - vendor/

stages:
  - Dependencies
  - Fixes
  - phplint
  - TwigLint

security-checker:
  stage: Dependencies
  script:
    - local-php-security-checker composer.lock
  allow_failure: false

composer-unused:
  stage: Dependencies
  script:
    - composer unused
  allow_failure: false

php-cs-fixer:
  stage: Fixes
  script:
    - php-cs-fixer fix src
  allow_failure: true

phpa:
  stage: Quality
  script:
    - bin/phpa
  allow_failure: true

phpcs:
  stage: Quality
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: true

phpcs-security-audit:
  stage: Quality
  script:
    - phpcs -v --extensions=php,inc,lib,module,info --standard=Security --ignore=./src/Kernel.php ./src
  allow_failure: true

phplint:
  stage: Quality
  script:
    - ./bin/phplint --exlude=../src/Kernel.php ../src

phpstan:
  stage: Quality
  script:
    - phpstan analyse ./src
  allow_failure: true

psalm:
  stage: Quality
  script:
    - psalm-plugin enable weirdan/doctrine-psalm-plugin
    - psalm-plugin enable weirdan/plugin-symfony
    - ./vendor/bin/psalm /src/
  allow_failure: true

# code-quality:
#   image: docker:latest
#   stage: Quality
#   variables:
#     DOCKER_DRIVER: overlay
#   services:
#     - docker:dind
#     - composer:latest
#   script:
#     - docker pull codeclimate/codeclimate
#     - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
#     - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
#   artifacts:
#     expire_in: 30 days
#     paths: [code-climate.json]
#   allow_failure: true

twig-lint:
  stage: TwigLint
  script:
    - twig-lint lint ./templates
  allow_failure: true

twigcs:
  stage: TwigLint
  script:
    - twigcs ./templates
