image: jakzal/phpqa:php8.0

before_script:
  - composer install

cache:
    paths:
        - vendor/

stages:
  - Security
  - Quality


security-checker:
  stage: Security
  script:
    - local-php-security-checker composer.lock
  allow_failure: false

phpcs:
  stage: Quality
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: true

phpstan:
  stage: Quality
  script:
    - phpstan analyse ./src
  allow_failure: true

twig-lint:
  stage: Quality
  script:
    - twig-lint lint ./templates
  allow_failure: true