version: '3.7'
services:
    database:
        image: 'mysql:latest'
        restart: "always"
        environment:
            MYSQL_DATABASE: snowtricks
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: 'database'
            PMA_USER: 'admin'
            PMA_PASSWORD: 'admin'
            PMA_DATABASE: 'snowtricks'
