version: "3.7"

services:
  database:
    image: "mysql:8.0"
    restart: "always"
    container_name: "snowtricks_db"
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - snowtricks_data:/mysql
  mailer:
    image: schickling/mailcatcher
    container_name: "snowtricks_mail_catcher"
    ports: [1025, 1080]
    volumes:
      - snowtricks_data:/mailer
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "snowtricks_phpmyadmin"
    restart: "always"
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: "admin"
      PMA_PASSWORD: "admin"
      PMA_DATABASE: "snowtricks"
    volumes:
      - snowtricks_data:/phpmyadmin
  http:
    image: nginx:l-alpine
    ports:
      - "80:80"
    volumes:
      - snowtricks_data:/nginx
    links:
      - database
      - mailer
      - phpmyadmin
  php:
    build: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv

  node:
    build: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv

networks:
  dev:

volumes:
  snowtricks_data:
    name: snowtricks_data
    driver: local
